GYCIL/GYCIL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('empresas/', include('companies.urls')),
    path('servicos/', include('services.urls')),
    path('login/', include('login.urls')),
    path('clientes/', include('clients.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GYCIL/companies/urls.py
from django.urls import path
from . import views

app_name = "companies"
urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro/", views.create, name="create"),
    path("procurar/", views.search, name="search"),
    path("procurar/<str:q>", views.search_q, name="search_q"),
]

GYCIL/services/urls.py
from . import views
from django.urls import path

app_name = "services"
urlpatterns = [
    path("", views.index, name="index"),
    path("meus_servicos", views.my_services, name="my_services"),
    path("<int:id>/descricao/", views.descriptions, name = "descriptions"),
    path("procurar/<str:q>", views.search, name="search"),
    path("orcamentos_servico/<int:id>", views.budgets_service, name="budgets_service"),
    path("aceitar_orcamento/<int:id>", views.accept_budget, name="accept_budget"),
    path("recusar_orcamento/<int:id>", views.refuse_budget, name="refuse_budget"),
    path("orcamento/<int:id>", views.budget, name="budget"),
    path("recusado/<int:id>", views.refuse, name="refuse"),
    path("cancelado/<int:id>", views.delete, name="delete"),
    path("finalizado/<int:id>", views.finish, name="finish"),
    path("cadastro_fornecedor/<int:id>", views.create_company, name="create_company"),
    path("cadastro/", views.create, name="create"),
    
]

GYCIL/companies/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from PIL import Image
import os
from django.core.files.base import ContentFile
from io import BytesIO


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True, blank=True)
    icon = models.ImageField(upload_to="icons_categories", blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
class Company(models.Model):
    STATE_CHOICES = {
        "AC": "Acre",
        "AL": "Alagoas",
        "AP": "Amapá",
        "AM": "Amazonas",
        "BA": "Bahia",
        "CE": "Ceará",
        "ES": "Espírito Santo",
        "GO": "Goiás",
        "MA": "Maranhão",
        "MT": "Mato Grosso",
        "MS": "Mato Grosso do Sul",
        "MG": "Minas Gerais",
        "PA": "Pará",
        "PB": "Paraíba",
        "PR": "Paraná",
        "PE": "Pernanbuco",
        "PI": "Piauí",
        "RJ": "Rio de Janeiro",
        "RN": "Rio Grande do Norte",
        "RS": "Rio Grande do Sul",
        "RO": "Rondônia",
        "RR": "Roraima",
        "SC": "Santa Catarina",
        "SP": "São Paulo",
        "SE": "Sergipe",
        "TO": "Tocantins",
        "DF": "Distrito Federal",
    }
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, default="0")
    fantasy_name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, blank=True)
    representative = models.CharField(max_length=255)
    cnpj = models.CharField(max_length=20, unique=True)
    zipcode = models.CharField(max_length=20)
    street = models.CharField(max_length=255)
    number = models.CharField(max_length=20)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=2, choices=STATE_CHOICES)
    phone = models.CharField(max_length=20)
    enabled = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    logo = models.ImageField(upload_to="companies_logos", blank=True, null=True)
    thumbnail = models.ImageField(upload_to="companies_logo_thumb", blank=True, null=True)
    categories = models.ManyToManyField(Category, blank=True)

    def __str__(self):
        return self.fantasy_name
        
    def save(self, *args, **kwargs):
        self.slug = slugify(f"{self.fantasy_name}_{self.user.id}")
                          
        super(Company, self).save(*args, **kwargs)

        # Criando a thumbnail
        self.__create_thumbnail()
        super(Company, self).save(*args, **kwargs)
        
    def __create_thumbnail(self):
        if not self.logo:
            return

        logo = Image.open(self.logo)
        size = (30, 30)
        logo.thumbnail(size)

        thumb_io = BytesIO()
        logo.save(thumb_io, logo.format, quality=85)
        extension = f".{logo.format.lower()}"


        self.thumbnail.save(f'{self.slug}_thumb{extension}', ContentFile(
            thumb_io.getvalue()), save=False)

    def __delete_file_if_exists(self, file):
        if file and os.path.isfile(file.path):
            os.remove(file.path)

    def delete(self, *args, **kwargs):
        self.__delete_file_if_exists(self.logo)
        self.__delete_file_if_exists(self.thumbnail)
        super(Company, self).delete(*args, **kwargs)

    class Meta:
        verbose_name = "Empresa"
        verbose_name_plural = "Empresas"
        

GYCIL/companies/forms.py
from django import forms
from .models import Company, Category
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from crispy_forms.helper import FormHelper
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit


class CompanyForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
        label="Categorias",
        queryset=Category.objects.all(), 
        widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = Company
        exclude = ["slug", "enabled", "created_at", "user", "thumbnail"]
        
        
        labels = {
            "company_name": "Rasão social",
            "fantasy_name": "Nome fantasia",
            "representative": "Representante legal",
            "cnpj": "CNPJ",
            "email": "E-mail",
            "zipcode": "Cep",
            "street": "Endereço",
            "number": "Número",
            "city": "Cidade",
            "state": "Estado",
            "phone": "Telefone",
            "logo": "Logomarca",
            "categories": "Categorias",
        }
        
        def save(self, commit=True):
        
            company = super().save(commit=False)
                
            if commit:
                company.save()
            
            return company
        
        def clean(self):
               
            company_email = self.cleaned_data.get('email')
            
            try:
                validate_email(company_email)
            except ValidationError:
                self.add_error('email', ValidationError('Informe um endereço de email válido'))
                
            return super().clean()
        
        def __init__(self, *args, **kwargs):
            super(CompanyForm, self).__init__(*args, **kwargs)
            self.helper = FormHelper()
            self.helper.form_method = 'post'
              
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput()
        }
        
        
    def __init__ (self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        
    def save(self, commit=True):
        password = self.cleaned_data.get('password')
        
        user = super().save(commit=False)
        
        if password:
            user.set_password(password)
            
        if commit:
            user.save()
            
        return user

GYCIL/companies/views.py
from django.shortcuts import render, get_list_or_404, redirect
from django.urls import reverse
from django.core.paginator import Paginator
from .forms import CompanyForm, UserForm
from django.contrib import messages
from django.db.models import Q
from .models import Company
from clients.models import Client

# Create your views here.
def index(request):
    
    user = request.user
    
    if user.username:
        if Client.objects.filter(user=user).exists():
            # login_user = Client.objects.filter(user=user)
            user_type = "client"
        else:
            return redirect("home")
    else:
        return redirect("home")
    
    companies = Company.objects.order_by("-id")

    # Aplicando a paginação
    paginator = Paginator(companies, 5)
    # /fornecedores?page=1 -> Obtendo a página da URL
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "companies": page_obj,
        "user_type": user_type
        
    }

    return render(request, "companies/index.html", context)


def search(request):
    
    user = request.user
    
    if user.username:
        if Client.objects.filter(user=user).exists():
            # login_user = Client.objects.filter(user=user)
            user_type = "client"
        else:
            user_type = "other"
    else:
        return redirect("login:index")
    
    search_value = str(request.GET.get("q").strip())
       
    if user_type != "client":
        if search_value:
            return redirect(reverse('services:search', kwargs={'q': search_value}))
        else:
            return redirect('services:index')
    
    
    if not search_value:
        return redirect("companies:index")
    
    
    
    companies = Company.objects \
        .filter(Q(fantasy_name__icontains=search_value) |
                Q(city__icontains=search_value)|
                Q(categories__name__icontains=search_value))\
        .order_by("-id")
           
    # Criando o paginator
    paginator = Paginator(companies, 30)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        "companies": page_obj,
        "user_type": user_type
        
    }
    
    return render(request, "companies/index.html", context)

def search_q(request, q):
    user = request.user
    
    if user.username:
        if Client.objects.filter(user=user).exists():
            # login_user = Client.objects.filter(user=user)
            user_type = "client"
        else:
            user_type = "other"
    else:
        return redirect("login:index")
    
    search_value = q
       
    if user_type != "client":
        if search_value:
            return redirect(reverse('services:search', kwargs={'q': search_value}))
        else:
            return redirect('services:index')
    
    
    if not search_value:
        return redirect("companies:index")
    
    
    
    companies = Company.objects \
        .filter(Q(fantasy_name__icontains=search_value) |
                Q(city__icontains=search_value)|
                Q(categories__name__icontains=search_value))\
        .order_by("-id")
           
    # Criando o paginator
    paginator = Paginator(companies, 30)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        "companies": page_obj,
        "user_type": user_type
        
    }
    
    return render(request, "companies/index.html", context)

def create(request):
    
    user = request.user
    
    if user.username:
        if Company.objects.filter(user=user).exists():
            # login_user = Client.objects.filter(user=user)
            return redirect("clients:index")
        user_type = "client"
    else:
        user_type = ""
       
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        company_form = CompanyForm(request.POST, request.FILES)

        if user_form.is_valid() and company_form.is_valid():
                       
            user = user_form.save()
            company = company_form.save(commit=False)
            company.user = user
            company.save()
            company_form.save_m2m()
            messages.success(request, 'Empresa cadastrada')
            return redirect('companies:index')
        
        context = {
        'user_form': user_form,
        'company_form': company_form
        }
        
        return render(request, 'companies/create.html', context)
            
    
    user_form = UserForm()
    company_form = CompanyForm()
    
    context = {
    'user_form': user_form,
    'company_form': company_form,
    'user_type': user_type
    }
    
    return render(request, 'companies/create.html', context)

GYCIL/companies/templates/companies/create.html
{% load static %}
{% include "partials/_head.html" %}
{% load crispy_forms_tags %}
{% block head %}
  <script src="{% static 'companies/js/create.js' %}"></script>
{% endblock %}
{% block content %}
  <div class="container-sm">
    <div class="text-center">
      <a href="{% url "home" %}" ><img class="img-fluid mb-3 mt-3" width="80px" src="{% static 'base/img/logo_diamond_crop.png' %}" alt=""></a>
    </div>
    <div class="text-center">
      <h4>Tem clientes te esperando =) <br> Cadastre-se!</h5>
        
      <p>Milhares de clientes buscando <br>
        o seu serviço!
      </p>
    </div>
    <div class="card">
      <div class="card-body shadow rounded">
        <form action="{{ form_action }}" method="post" enctype="multipart/form-data" novalidate >
          {% csrf_token %}
          <div class="row mb-3">
            <div class="col-lg-6">{{ user_form.username|as_crispy_field }}</div>
            <div class="col-lg-6">{{ company_form.fantasy_name|as_crispy_field }}</div>
            <div class="col-lg-6">{{ company_form.representative|as_crispy_field }}</div>
            <div class="col-lg-6">{{ company_form.cnpj|as_crispy_field }}</div>
          </div>
          <hr>
          <div class="row mb-3">
            <div class="col-lg-3">{{ company_form.zipcode|as_crispy_field }}</div>
            <div class="col-lg-6">{{ company_form.street|as_crispy_field }}</div>
            <div class="col-lg-3">{{ company_form.number|as_crispy_field }}</div>
            <div class="col-lg-4">{{ company_form.city|as_crispy_field }}</div>
            <div class="col-lg-4">{{ company_form.state|as_crispy_field }}</div>
          </div>
          <hr class="line">
          <div class="row mb-3">
            <div class="col-lg-6">{{ company_form.phone|as_crispy_field }}</div>
            <div class="col-lg-6">{{ user_form.email|as_crispy_field }}</div>
            <div class="col-lg-6">{{ user_form.password|as_crispy_field }}</div>
            <div class="col-lg-4">{{ company_form.categories |as_crispy_field }}</div>
            <div class="col-lg-4">{{ company_form.logo|as_crispy_field }}</div>
          </div>
          <div class="text-center">
            <button type="submit" class="btn submitBtn mt-3 mb-3">Cadastrar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="mb-3">
    {% include "partials/_footer.html" %}
  </div>
{% endblock %}

GYCIL/companies/templates/companies/index.html
{% extends 'base.html' %}
{% block title %}
  Empresas
{% endblock %}
{% load static %}
{% block head %}
{% endblock %}

{% block content %}
  <div class="container-fluid bottom-sm">
    <div class="col-sm-12 col-md-8 text-center">
      <h5>Precisando de <br> empresas especializadas?</h5>
    </div>
    <div class="text-center">
      <i class="bi bi-star-fill"></i>
      <p>Empresas avaliadas</p>
      <i class="bi bi-shield-fill-check"></i>
      <p>Contratos 100% seguros</p>
      <i class="bi bi-wallet-fill"></i>
      <p>Preços Justos</p>
    </div>
  </div>

  <div class="container row d-flex justify-content-center ms-1 me-1">
    <div class="card">
      <div class="card-body rounded card-background shadow">
        <div class="card shadow rounded">
          <div class="card-body rounded shadow bg-white">

            <div class="text-center p-4">
              <h5>Qual empresa você <br> está buscando?</h5>
            </div>
            <div class="input-group mb-4">
              <form class="d-flex" role="search" action="{% url 'companies:search' %}">
                <input value="{{ request.GET.q }}" class="form-control me-2" type="text" placeholder="Procure aqui" aria-label="Search" name="q"/>
                <button class="btn btn-success" type="submit">Procurar</button>
              </form>
            </div>

            {% for company in companies %}
              <div class="col-lg-4">
                <div class="contaier text-center bg-white mb-4 shadow-sm border ">
                  <div class="d-flex align-items-center mx-auto p-2 card-body justify-content-between">
                    <div class="text-center">
                      {% if company.logo %}
                        <img src="{{ company.logo.url }}" class="img img-fluid" height="50" width="50" alt="{{ company.fantasy_name }}" class="imf-fluid rounded" />
                      {% else %}
                        <img src="{% static 'base/img/logo_diamond_crop.png' %}" class="img img-fluid" alt="{{ company.fantasy_name }}" height="50" width="50" alt="{{ company.fantasy_name }}" class="imf-fluid rounded" />
                      {% endif %}
                    </div>
                    {% comment %} <p>{{ company.city }}</p> {% endcomment %}
                      <p class="m-0">{{ company.fantasy_name }}</p>
                    <a href="{% url "services:create_company" company.id %}"><i class="bi bi-arrow-right"></a></i>
                  </div>
                </div>
              </div>
            {% endfor %}
            {% if companies.paginator.num_pages > 1 %}
              <nav aria-label="Paginação da página">
                <ul class="pagination justify-content-end">
                  {% if companies.has_previous %}
                    <li class="page-item">
                      <a href="?page={{ companies.previous_page_number }}&q={{ request.GET.q }}" class="page-link" aria-label="Anterior">&laquo;</a>
                    </li>
                  {% endif %}
                  <li class="page-item active">
                    <span class="page-link">{{ companies.number }}</span>
                  </li>
                  {% if companies.has_next %}
                    <li class="page-item">
                      <a href="?page={{ companies.next_page_number }}&q={{ request.GET.q }}" class="page-link" aria-label="Próximo">&raquo;</a>
                    </li>
                  {% endif %}
                </ul>
              </nav>
            {% endif %}
          </div>
        </div>
      </div>
    </div>



  </div>

  {% include "partials/_footer.html" %}
{% endblock %}