GYCIL/GYCIL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('empresas/', include('companies.urls')),
    path('servicos/', include('services.urls')),
    path('login/', include('login.urls')),
    path('clientes/', include('clients.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GYCIL/services/urls.py
from . import views
from django.urls import path

app_name = "services"
urlpatterns = [
    path("", views.index, name="index"),
    path("meus_servicos", views.my_services, name="my_services"),
    path("<int:id>/descricao/", views.descriptions, name = "descriptions"),
    path("procurar/<str:q>", views.search, name="search"),
    path("orcamentos_servico/<int:id>", views.budgets_service, name="budgets_service"),
    path("aceitar_orcamento/<int:id>", views.accept_budget, name="accept_budget"),
    path("recusar_orcamento/<int:id>", views.refuse_budget, name="refuse_budget"),
    path("orcamento/<int:id>", views.budget, name="budget"),
    path("recusado/<int:id>", views.refuse, name="refuse"),
    path("cancelado/<int:id>", views.delete, name="delete"),
    path("finalizado/<int:id>", views.finish, name="finish"),
    path("cadastro_fornecedor/<int:id>", views.create_company, name="create_company"),
    path("cadastro/", views.create, name="create"),
    
]

GYCIL/services/models.py
from django.db import models
from django.utils.text import slugify
from companies.models import Company, Category
from clients.models import Client
from django.utils import timezone
class Service(models.Model):
    STATE_CHOICES = {
        "AC": "Acre",
        "AL": "Alagoas",
        "AP": "Amapá",
        "AM": "Amazonas",
        "BA": "Bahia",
        "CE": "Ceará",
        "ES": "Espírito Santo",
        "GO": "Goiás",
        "MA": "Maranhão",
        "MT": "Mato Grosso",
        "MS": "Mato Grosso do Sul",
        "MG": "Minas Gerais",
        "PA": "Pará",
        "PB": "Paraíba",
        "PR": "Paraná",
        "PE": "Pernanbuco",
        "PI": "Piauí",
        "RJ": "Rio de Janeiro",
        "RN": "Rio Grande do Norte",
        "RS": "Rio Grande do Sul",
        "RO": "Rondônia",
        "RR": "Roraima",
        "SC": "Santa Catarina",
        "SP": "São Paulo",
        "SE": "Sergipe",
        "TO": "Tocantins",
        "DF": "Distrito Federal",
    }
    
    slug = models.SlugField(unique=True, blank=True)
    street = models.CharField(max_length=255)
    rating = models.CharField(max_length=255, blank=True)
    number = models.CharField(max_length=255, blank=True)
    price = models.CharField(max_length=255, blank=True)
    status = models.CharField(max_length=255, default="Aguardando orçamento")
    date = models.CharField(max_length=255, blank=True)
    description = models.TextField(max_length=3000)
    hours_service = models.CharField(max_length=255, blank=True)
    cep = models.CharField(max_length=255)
    state = models.CharField(max_length=2, choices=STATE_CHOICES)
    city = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)
    client = models.ForeignKey(Client, on_delete=models.DO_NOTHING)
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    imagem = models.ImageField(upload_to='services_files', blank=True, null=True)
    nfe = models.FileField(upload_to='services_files', blank=True, null=True)
    nfse = models.FileField(upload_to='services_files', blank=True, null=True)
    companies_refused = models.ManyToManyField(Company, related_name='refused_services', blank=True)
    
    def save(self, *args, **kwargs):
        super(Service, self).save(*args, **kwargs)
        self.slug = slugify(f'{self.id}_{self.category}')          
        super(Service, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.id}_{self.category}'

    class Meta:
        verbose_name = "Serviço"
        verbose_name_plural = "Serviços"
        


class Budget(models.Model):
    service = models.ForeignKey(Service, on_delete=models.DO_NOTHING)
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING)
    slug = models.SlugField(unique=True)
    price = models.CharField(max_length=255, blank=True)
    status = models.CharField(max_length=255, default="aguardando orçamento")
    date = models.CharField(max_length=255, blank=True)
    budget_file = models.FileField(upload_to='budgets_files/', blank=True)
    hours_service = models.CharField(max_length=255, blank=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.service.id}_{self.company.fantasy_name}')          
        super(Budget, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.service.id}_{self.company.fantasy_name}'

    class Meta:
        verbose_name = "Orçamento"
        verbose_name_plural = "Orçamentos"
        

GYCIL/services/forms.py
from django import forms
from .models import Budget, Service
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class BudgetForm(forms.ModelForm):
    class Meta:
        model = Budget
        exclude = ["slug", "status", "company", "service"]
        
        
        labels = {
            "price": "Valor final",
            "date": "Data de inicio",
            "budget_file": "Arquivo de orçamento",
            "hours_service": "Horas de serviço",
        }
        
        def save(self, commit=True):
        
            budget = super().save(commit=False)
                
            if commit:
                budget.save()
            
            return budget
        

class FinishForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ["nfe", "nfse"]
        
        
        labels = {
            "nfe": "Nota Fiscal de Produto",
            "nfse": "Nota Fiscal de Serviço",
        }
        
    def clean(self):
        cleaned_data = super().clean()
        nfe = self.cleaned_data.get('nfe',"")
        nfse = self.cleaned_data.get('nfse',"")

        if not nfe and not nfse:
            raise ValidationError('Pelo menos um dos campos deve ser preenchido.')
        
        return cleaned_data
    
    def save(self, commit=True):
    
        service = super().save(commit=False)
            
        if commit:
            service.save()
        
        return service
            
class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        exclude = ["slug", "rating", "price", "status", "date", "hours_service", "created_at", "client", "company", "companies_refused", "nfe", "nfse"]
        
        
        labels = {
            "category": "Categoria",
            "description": "Descrição",
            "street": "Endereço",
            "cep": "CEP",
            "state": "Estado",
            "city": "Cidade",
            "number": "Número",
            "imagem": "Imagem",
        }
        
        def save(self, commit=True):
        
            service = super().save(commit=False)
                
            if commit:
                service.save()
            
            return service

GYCIL/services/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.core.paginator import Paginator
from django.contrib import messages
from .models import Service, Budget
from companies.models import Company
from django.db import transaction
from django.db.models import Q
from django.http import JsonResponse
from .forms import BudgetForm, ServiceForm, FinishForm
from django.utils.text import slugify
from clients.models import Client
from django.conf import settings

# Create your views here.

def index(request):
    
    user = request.user
    if user.username:
        if Client.objects.filter(user=user).exists():
            client = get_object_or_404(Client, user=user) 
            user_type = "client"
            services = Service.objects.filter(client=client).exclude(Q(status="Cancelado"))
        else:
            company = get_object_or_404(Company, user=user)
            budgets = Budget.objects.filter(company=company)
            
            user_type = "company"
            services = Service.objects.filter(
                                    Q(city=company.city) &
                                    Q(state=company.state) &
                                    Q(category__in=company.categories.all()) &
                                    Q(company=None)
                                      ).exclude(
                                          Q(companies_refused=company) |
                                          Q(id__in=[budget.service.id for budget in budgets])|
                                          Q(status="Cancelado"))
    else:
        return redirect("login:index")
    
    form_action = reverse("services:index")
            
    paginator = Paginator(services, 30)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    for service in page_obj:
        name = service.client.name.split()
        service.client.name = name[0] + " " + name[1][:2] + "***"

    context = {
        "services": page_obj,
        "form_action": form_action,
        "user_type": user_type
    }

    return render(request, "services/index.html", context)

def search(request, q):
    
    search_value = q
         
    if not search_value:
        return redirect("services:index")
    
    company = get_object_or_404(Company, user=request.user)
    budgets = Budget.objects.filter(company=company)
       
    services = Service.objects \
        .filter((Q(id__icontains=search_value) |
                Q(city__icontains=search_value)|
                Q(category__name__icontains=search_value)) &
                Q(company=None)
                ).exclude(  Q(status="Cancelado")|
                            Q(companies_refused=company) |
                            Q(id__in=[budget.service.id for budget in budgets])|
                            Q(status="Cancelado"))

        
           
    # Criando o paginator
    paginator = Paginator(services, 30)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    for service in page_obj:
        name = service.client.name.split()
        service.client.name = name[0] + " " + name[1][:2] + "***"
    
    
    context = {
        "services": page_obj,
        "user_type": "company"
        }
    
    
    return render(request, "services/index.html", context)

def refuse(request, id):
    
    company = get_object_or_404(Company, user=request.user)     
    service = get_object_or_404(Service, pk=id)
    if Budget.objects.filter(service=service).exists():
        budget = get_object_or_404(Budget, service=service)
        budget.status="Cancelado"
        budget.save()
    
    with transaction.atomic():
        service.companies_refused.add(company)
    service.save()
    
    return redirect("services:index")

def delete(request, id):
    service = get_object_or_404(Service, pk=id)
    client = get_object_or_404(Client, user=request.user)
     
    if service.client == client:
        service.status="Cancelado"
        service.save()
    
    return redirect("services:index")

def my_services(request):
    
    user = request.user
    if user.username:
        if Client.objects.filter(user=user).exists():
            return redirect("services:index")
        else:
            company = get_object_or_404(Company, user=user)
            budgets = Budget.objects.filter(company=company)    
            user_type = "company"
            services = Service.objects.filter( (Q(company=company) |
                                               Q(company=None)) &
                                               Q(id__in=[budget.service.id for budget in budgets])
                                              ).exclude(Q(companies_refused=company) |
                                                        Q(status="Cancelado"))
    else:
        return redirect("login:index")
    
    form_action = reverse("services:my_services")
    
    paginator = Paginator(services, 30)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    for service in page_obj:
        name = service.client.name.split()
        service.client.name = name[0] + " " + name[1][:2] + "***"

    context = {
        "services": page_obj,
        "form_action": form_action,
        "user_type": user_type
    }

    return render(request, "services/index.html", context)

def budgets_service(request, id):
    service = get_object_or_404(Service, pk=id)
    budgets = Budget.objects.filter(service=service).exclude(status=["Recusado","Cancelado"])
    
    filter_budgets_empty = [budget for budget in budgets if budget.price != ""]
    filter_budgets_not_accept = [budget for budget in filter_budgets_empty if budget.status != "Recusado"]
            
         
    budgets_serialized = [{
        'company': budget.company.fantasy_name,
        'price': budget.price,
        'date': budget.date,
        'url_accept': reverse("services:accept_budget", kwargs={'id': int(budget.id)}),  
        'url_refuse': reverse("services:refuse_budget", kwargs={'id': int(budget.id)}),
        'budget_file': settings.MEDIA_URL + str(budget.budget_file)
    } for budget in filter_budgets_not_accept]
    
    
    return JsonResponse(budgets_serialized, safe=False)

def descriptions(request, id):
    service = Service.objects.filter(id=id).order_by('-id')
     
    name = service[0].client.name.split()
    new_name = name[0] + " " + name[1][:2] + "***" 
    
    if service[0].company:
        company=service[0].company.fantasy_name
    else:
        company=""
        
    user = request.user
    if user.username:
        if Client.objects.filter(user=user).exists():
            status = service[0].status
        else:
            company_user = get_object_or_404(Company, user=request.user)
            
            if Budget.objects.filter(Q(service=service[0]) &
                                     Q(company=company_user)).exists(): 
                
                budget = get_object_or_404(Budget, Q(service=service[0]) &
                                                   Q(company=company_user))
                status = budget.status
                
            else:
                status = service[0].status
                
    print(service[0].status)
    print(status)
    
    if status == "Aceito":
        if service[0].status == "Serviço em andamento":
            url_accept = reverse("services:finish", kwargs={'id': int(service[0].id)})
        else:
            url_accept = ""
            status = service[0].status
    else:
        url_accept = reverse("services:budget", kwargs={'id': int(service[0].id)})
             
    service_serialized = [{
        'id': str(descriptions.id),
        'street': descriptions.street,
        'cep': descriptions.cep,
        'state': descriptions.state,
        'city': descriptions.city,
        'created_at': str(descriptions.created_at),
        'description': descriptions.description,
        'client': new_name,
        'status': status,
        'date_start': descriptions.date,
        'hours_service': descriptions.hours_service,
        'company': company,
        'price': descriptions.price,
        'category': descriptions.category.name,
        'url_refuse': reverse("services:refuse", kwargs={'id': int(descriptions.id)}),
        'url_accept': url_accept,
        'url_delete': reverse("services:delete", kwargs={'id': int(descriptions.id)}),
    } for descriptions in service]
    
    
    return JsonResponse(service_serialized, safe=False)

def finish(request, id):
    company = get_object_or_404(Company, user=request.user)
    service = get_object_or_404(Service, pk=id)
    
    if not service.company == company:
       return redirect ("services:index") 
   
    if request.method == 'POST':
        form = FinishForm(request.POST, request.FILES, instance=service)

        if form.is_valid():
            form.clean()
            service = form.save()
            service.status = "Concluido"
            print(service.status)
            service.save()
            return redirect('services:index')
        
        
        form = FinishForm(instance=service)
        context = {
        'form': form,
        'user_type': 'company'
        }
        messages.error(request, "Falha ao finalizar. Deve ter ao menos uma Nota Fiscal.")
        
        return render(request, 'services/finish.html', context)
            
    
    form = FinishForm(instance=service)   
    context = {
    'form': form,
    'user_type': 'company'
    }
        
    return render(request, 'services/finish.html', context)


def budget(request, id):
    
    company = get_object_or_404(Company, user=request.user)     
    service = get_object_or_404(Service, pk=id)
    slug = slugify(f"{service.id}_{company.fantasy_name}")
    
    if not Budget.objects.filter(slug=slug).exists():
        budget = Budget(service=service, company=company)

GYCIL/services/templates/services/budget.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  Cadastro de Orçamento
{% endblock %}
{% block head %}
  <script src="{% static 'services/js/budget.js' %}"></script>
  {% endblock %}
  {% block content %}
  <div class="m-3">
    <form action="{{ form_action }}" method="post" enctype="multipart/form-data" novalidate>
      {% csrf_token %}
      <div class="col-lg-6">{{ form.price|as_crispy_field }}</div>
      <div class="col-lg-6">{{ form.date|as_crispy_field }}</div>
      <div class="col-lg-6">{{ form.budget_file|as_crispy_field }}</div>
      <div class="col-lg-6">{{ form.hours_service|as_crispy_field }}</div>
      <button type="submit" class="btn btn-primary mt-5">Enviar Orçamento</button>
    </form>
  </div>



  {% endblock %}

GYCIL/services/templates/services/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  Cadastro de Serviço
{% endblock %}
{% block head %}
  {% endblock %}
  {% block content %}
  <div class="container-fluid">
    <div class="container-fluid bottom-sm">
      <div class="col-sm-12 col-md-8 text-center">
        <h5>Escreva seus problemas e as <br> empresas vão até você!</h5>
      </div>
      <div class="text-center">
        <i class="bi bi-star-fill"></i>
        <p>Empresas avaliadas</p>
        <i class="bi bi-shield-fill-check"></i>
        <p>Contratos 100% seguros</p>
        <i class="bi bi-wallet-fill"></i>
        <p class="">Preços Justos</p>
      </div>
    </div>
    <div class="card">
      <div class="card-body card-background rounded shadow">
        <div class="card">
          <div class="card-body rounded shadow">
            <form action="{{ form_action }}" method="post" enctype="multipart/form-data" novalidate>
              {% csrf_token %}
              {{form|crispy}}
              <div class="text-center">
                <button type="submit" class="btn submitBtn mt-2 mb-2">Solicitar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% include "partials/_footer.html" %}

  {% endblock %}

GYCIL/services/templates/services/finish.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  Finalizar Serviço
{% endblock %}
{% block head %}
  {% endblock %}
  {% block content %}
  <div class="container-fluid">
    <div class="container-fluid bottom-sm">
      <div class="col-sm-12 col-md-8 text-center">
        <h5>Parabéns pela venda! <br> Encaminhe as NFs</h5>
      </div>
      <div class="text-center">
        <i class="bi bi-star-fill"></i>
        <p>Empresas avaliadas</p>
        <i class="bi bi-shield-fill-check"></i>
        <p>Contratos 100% seguros</p>
        <i class="bi bi-wallet-fill"></i>
        <p class="">Preços Justos</p>
      </div>
    </div>
    <div class="card">
      <div class="card-body card-background rounded shadow">
        <div class="card">
          <div class="card-body rounded shadow">
            <form action="{{ form_action }}" method="post" enctype="multipart/form-data" novalidate>
              {% csrf_token %}
              {{form|crispy}}
              <div class="text-center">
                <button type="submit" class="btn submitBtn mt-2 mb-2">Finalizar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% include "partials/_footer.html" %}

  {% endblock %}

GYCIL/services/templates/services/index.html
{% extends 'base.html' %}
{% block title %}
  Serviços
{% endblock %}
{% load static %}
{% block head %}
  <script src="{% static 'services/js/index.js' %}"></script>
{% endblock %}

{% block content %}
  {% with budget_url='/servicos/meus_servicos' %}
    {% if  user_type == "client" %}
    <h2 class="mb-3 text-center">Serviços que solicitei</h2>
    {% elif budget_url == form_action %}
    <h2 class="mb-3 text-center">Serviços capturados</h2>
    {% else %}
    <h2 class="mb-3 text-center">Serviços pendentes na comunidade</h2>
    {% endif %}
    <div class="card shadow">
      <div class="card-body card-background rounded">
        <div class="table-responsive rounded">
          <table class="table table-striped table rounded">
            <thead>
              <tr class="text-center">
                <th class="d-none d-sm-table-cell">ID</th>
                <th>Categoria</th>
                <th class="d-none d-sm-table-cell">Estado</th>
                <th class="d-none d-sm-table-cell">Cidade</th>
                <th>Solicitante</th>
                <th class="d-none d-sm-table-cell">Abertura</th>
                <th>Ações</th>
              </tr>
            </thead>
            <tbody>
              {% for service in services %}
                <tr>
                  <td class="d-none d-sm-table-cell">{{ service.id }}</td>
                  <td>{{ service.category.name }}</td>
                  <td class="d-none d-sm-table-cell">{{ service.state }}</td>
                  <td class="d-none d-sm-table-cell">{{ service.city }}</td>
                  <td>{{ service.client.name }}</td>
                  <td class="d-none d-sm-table-cell">{{ service.created_at }}</td>
    
                  <td class="d-flex gap-2 p-2">
                    <button data-url="{% url 'services:descriptions' service.id %}" type="button" class="btn btn-primary align-items-center" data-bs-toggle="modal" data-bs-target="#serviceModal"><i class="bi bi-info-circle"></i></button>
    
                    {% if user_type == "client" and not service.price %}
                      <button data-url="{% url 'services:budgets_service' service.id %}" type="button" class="btn btn-success align-items-center" data-bs-toggle="modal" data-bs-target="#budgetModal"><i class="bi bi-newspaper"></i></button>
                    {% endif %}
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="8" class="text-center">Nenhum serviço disponível.</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
          {% if services.paginator.num_pages > 1 %}
            <nav aria-label="Paginação da página">
              <ul class="pagination justify-content-end">
                {% if services.has_previous %}
                  <li class="page-item">
                    <a href="?page={{ services.previous_page_number }}&q={{ request.GET.q }}" class="page-link" aria-label="Anterior">&laquo;</a>
                  </li>
                {% endif %}
                <li class="page-item active">
                  <span class="page-link">{{ services.number }}</span>
                </li>
                {% if services.has_next %}
                  <li class="page-item">
                    <a href="?page={{ services.next_page_number }}&q={{ request.GET.q }}" class="page-link" aria-label="Próximo">&raquo;</a>
                  </li>
                {% endif %}
              </ul>
            </nav>
          {% endif %}
        </div>
      </div>
    </div>

    <!-- Button trigger modal -->

    <!-- Modal -->
    <div class="modal fade modal-lg" id="serviceModal" tabindex="-1" aria-labelledby="serviceModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content text-center">
          <div class="modal-header align-items-center">
            <h4 class="modal-title fs-5 text-center" id="serviceModalLabel">Serviço de {{ service.category }} - {{ service.id }}</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
                <div class="card">
                  <div class="card-body rounded shadow">
                    <div>
                      <div>
                        <h5>Cidade - Estado</h5>
                      </div>
                      <div>
                        <p id="state_city"></p>
                      </div>
                      <hr class="line">
                    </div>
                    <div>
                      <div>
                        <h5>Endereço</h5>
                      </div>
                      <div>
                        <p id="street"></p>
                      </div>
                    </div>
                    <hr class="line">
                    <div>
                      <div>
                        <h5>CEP</h5>
                      </div>
                      <div>
                        <p id="cep"></p>
                      </div>
                    </div>
                    <hr class="line">
                    <div>
                      <div>
                        <h5>Cliente</h5>
                      </div>
                      <div>
                        <p id="client"></p>
                      </div>
                    </div>
                    <hr class="line">
                    <div>
                      <div>
                        <h5>Descrição</h5>
                      </div>
                      <div>
                        <p id="description"></p>
                      </div>
                    </div>
                    <hr class="line">
                    <div>
                      <div>
                        <h5>Momento da solicitação</h5>
                      </div>
                      <div>
                        <p id="created_at"></p>
                      </div>
                    </div>
                    <hr class="line">
                    <div>
                      <div>
                        <h5>Status</h5>
                      </div>
                      <div>
                        <p id="status"></p>
                      </div>
                    </div>
                    <hr class="line">
                    <div>
                      <div>
                        <h5>Data de início</h5>
                      </div>
                      <div>
                        <p id="date_start"></p>
                      </div>
                    </div>
                    <hr class="line">
                    <div>
                      <div>
                        <h5>Horas de serviço</h5>
                      </div>
                      <div>
                        <p id="hours_service"></p>
                      </div>
                    </div>
                    <hr class="line">
                    <div>
                      <div>
                        <h5>Empresa</h5>
                      </div>
                      <div>
                        <p id="company"></p>
                      </div>
                    </div>
                    <hr class="line">
                    <div>
                      <div>
                        <h5>Valor final</h5>
                      </div>
                      <div>
                        <p id="price"></p>
                      </div>
                    </div>
                  </div>
                </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary me-3" data-bs-dismiss="modal">Fechar</button>
            <div class="ms-auto">
              {% if form_action == budget_url %}
                <a href="" type="button" class="btn btn-danger ms-3" id="button_refuse">Abandonar</a>
                <a href="" type="button" class="btn btn-success ms-3" id="button_accept">Editar Orçamento</a>
              {% elif user_type == "client" %}
                <a href="" type="button" class="btn btn-danger ms-3" id="button_delete">Deletar</a>
              {% else %}
                <a href="" type="button" class="btn btn-danger ms-3" id="button_refuse">Recusar</a>
                <a href="" type="button" class="btn btn-success ms-3" id="button_accept">Aceitar</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal Fornecedores -->
    {% if user_type == "client" %}
      <div class="modal fade" id="budgetModal" tabindex="-1" aria-labelledby="budgetModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title fs-5" id="budgetModalLabel">Orçamentos para Aprovação</h4>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <div class="card">
                <div class="card-body rounded shadow">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>Empresa</th>
                        <th>Valor</th>
                        <th>Data início</th>
                        <th>Opções</th>
                      </tr>
                    </thead>
                    <tbody id="budgetTableBody"></tbody>
                  </table>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
  {% endwith %}
  {% include "partials/_footer.html" %}
{% endblock %}