GYCIL/GYCIL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('empresas/', include('companies.urls')),
    path('servicos/', include('services.urls')),
    path('login/', include('login.urls')),
    path('clientes/', include('clients.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GYCIL/clients/urls.py
from django.urls import path
from . import views

app_name = "clients"
urlpatterns = [
    path("cadastro/", views.create, name="create"),
]

GYCIL/companies/urls.py
from django.urls import path
from . import views

app_name = "companies"
urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro/", views.create, name="create"),
    path("procurar/", views.search, name="search"),
    path("procurar/<str:q>", views.search_q, name="search_q"),
]

GYCIL/login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path('', views.login, name='index'),
    path('logout/', views.logout, name='logout'),
     
]

GYCIL/services/urls.py
from . import views
from django.urls import path

app_name = "services"
urlpatterns = [
    path("", views.index, name="index"),
    path("meus_servicos", views.my_services, name="my_services"),
    path("<int:id>/descricao/", views.descriptions, name = "descriptions"),
    path("procurar/<str:q>", views.search, name="search"),
    path("orcamentos_servico/<int:id>", views.budgets_service, name="budgets_service"),
    path("aceitar_orcamento/<int:id>", views.accept_budget, name="accept_budget"),
    path("recusar_orcamento/<int:id>", views.refuse_budget, name="refuse_budget"),
    path("orcamento/<int:id>", views.budget, name="budget"),
    path("recusado/<int:id>", views.refuse, name="refuse"),
    path("cancelado/<int:id>", views.delete, name="delete"),
    path("finalizado/<int:id>", views.finish, name="finish"),
    path("cadastro_fornecedor/<int:id>", views.create_company, name="create_company"),
    path("cadastro/", views.create, name="create"),
    
]

GYCIL/base/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      GYCIL -{% block title %}
      {% endblock %}
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'base/img/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'base/css/login.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base/js/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'base/js/jquery.mask.js' %}"></script>


    {% block head %}
    {% endblock %}
  </head>
  <body>
    {% comment %}Navbar{% endcomment %}
    {% block nav %}
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url "home" %}"><img src="{% static 'base/img/logo_oficial.png' %}" alt="Logo" width="30" height="24" class="logo" /></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">

            {% if user_type == "client" %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'login:logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'services:create' %}">Solicite serviço</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'services:my_services' %}">Serviços solicitados</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'companies:index' %}">Procurar empresas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'companies:create' %}">Seja um profissional</a>
              </li>
            </ul>
            {% elif user_type == "company" %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'login:logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'services:my_services' %}">Meus serviços</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'services:index' %}">Procurar serviços</a>
              </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'login:index' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'companies:create' %}">Seja um profissional</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'clients:create' %}">Seja um cliente</a>
              </li>
            </ul>
            {% endif %}
            
            <form class="d-flex" role="search" action="{% url 'companies:search' %}">
              <input value="{{ request.GET.q }}" class="form-control me-2" type="text" placeholder="Procure aqui" aria-label="Search" name="q"/>
              <button class="btn btn-outline-success" type="submit">Procurar</button>
            </form>
          </div>
        </div>
      </nav>
      <hr class="line m-0">
    {% endblock %}
    <main>
      <div class="row mb-3 justify-content-center">
        <div class="col-lg-2 d-none d-lg-block"></div>
        <div class="col-lg-8 p-4">
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-lg-2 d-none d-lg-block"></div>
      </div>
    </main>
  </body>
</html>

GYCIL/base/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Cadastro de Clientes
{% endblock %}
{% block content %}
  <main class="container-fluid">
    <header class="gap-2 m-0">
      <div>
        <h3>Diversos tipos de Serviços e empresas em um só lugar</h3>

        <p>Encontre as melhores empresas e contrate serviços para tudo que precisar.</p>
      </div>

      <img class="img img-fluid" width="700" src="{% static 'base/img/header-image.png' %}" alt="header-image" />
    </header>

    <form role="search" action="{% url 'companies:search' %}">
      <div class="row mb-4">
        <div class="col-lg-4 mb-4">
          <div class="input-group">
            <i class="bi bi-search input-group-text"></i>
            <input value="{{ request.GET.q }}" type="text" placeholder="Procure aqui" aria-label="Search" name="q" class="form-control" />
          </div>
        </div>
        <div class="col-lg-4">
          <input class="form-control btn submitBtn" type="submit" value="Pesquisar" />
        </div>
      </div>
    </form>

    <section class="container-fluid rounded mt-5 shadow">
      <div class="card first-md text-center">
        <div class="card-header">
          <div class="row center-sm middle-sm mt-3 mb-3">
            <h5>Todas as categorias de serviços</h5>
          </div>
        </div>
        <div class="row row-cols-3">
          <div class="col-sm-4 col-md-1 false">
            <div class="row center-sm text-center">
              <a href="{% url 'companies:search_q' 'Assistência Técnica' %}">
                <i class="bi bi-gear-wide"></i>
                <p>
                  Assistência <br /> Técnica
                </p>
              </a>
            </div>
          </div>
          <div class="col-sm-4 col-md-1 false">
            <div class="row center-sm text-center">
              <a href="{% url 'companies:search_q' 'Autos' %}">
                <i class="bi bi-car-front-fill"></i>
                <p>Autos</p>
              </a>
            </div>
          </div>
          <div class="col-sm-4 col-md-1 false">
            <div class="row center-sm text-center">
              <a href="{% url 'companies:search_q' 'Aulas e Disciplinas' %}">
                <i class="bi bi-pencil-fill"></i>
                <p>
                  Aulas e <br /> Disciplinas
                </p>
              </a>
            </div>
          </div>
          <div class="col-sm-4 col-md-1 false">
            <div class="row center-sm text-center">
              <a href="{% url 'companies:search_q' 'Tecnologia' %}">
                <i class="bi bi-display"></i>
                <p>Tecnologia</p>
              </a>
            </div>
          </div>
          <div class="col-sm-4 col-md-1 false">
            <div class="row center-sm text-center">
              <a href="{% url 'companies:search_q' 'Eventos' %}">
                <i class="bi bi-cup-straw"></i>
                <p>Eventos</p>
              </a>
            </div>
          </div>
          <div class="col-sm-4 col-md-1 false">
            <div class="row center-sm text-center">
              <a href="{% url 'companies:search_q' 'Serviços Domésticos' %}">
                <i class="bi bi-house"></i>
                <p>
                  Serviços <br /> Domésticos
                </p>
              </a>
            </div>
          </div>
          <div class="col-sm-4 col-md-1 false">
            <div class="row center-sm text-center">
              <a href="{% url 'companies:search_q' 'Moda e Beleza' %}">
                <i class="bi bi-handbag"></i>
                <p>
                  Moda e <br /> Beleza
                </p>
              </a>
            </div>
          </div>
          <div class="col-sm-4 col-md-1 false">
            <div class="row center-sm text-center">
              <a href="{% url 'companies:search_q' 'Reforma e Reparos' %}">
                <i class="bi bi-tools"></i>
                <p>
                  Reforma e <br /> Reparos
                </p>
              </a>
            </div>
          </div>
          <div class="col-sm-4 col-md-1 false">
            <div class="row center-sm text-center">
              <a href="{% url 'companies:search_q' 'Saúde' %}">
                <i class="bi bi-heart-pulse"></i>
                <p>Saúde</p>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="mt-5">
      <div class="text-center">
        <h4>Quem contratou <br /> recomenda</h4>

        <p>
          São mais de 500 mil clientes <br /> e profissionais satisfeitos
        </p>
      </div>
      <div class="container-sm mt-3">
        <h1>"</h1>
        <i>
          <p>
            Fui muito bem atendido, a empresa 
            foi muito profissional e 
            fez um bom trabalho de qualidade. 
            Orçamento grátis e não é careiro. <br /><br />
            <b>Serviço de Assistência Técnica:</b> Lucas Cipriano contratou um serviço de São Paulo, SP
          </p>
        </i>

        <h1>"</h1>
        <i>
          <p>
            As empresas são muito bem organizadas e 
            dedicadas com seus serviços, tudo que é 
            pedido é feito de maneira como pedido. 
            Aprovado! <br /><br />
            <b>Serviço de Eventos:</b> Igor Faggiani contratou um serviço de Santa Catarina, SC
          </p>
        </i>

        <h1>"</h1>
        <i>
          <p>
            Um excelente profissional, e acima de tudo 
            confiável. Foi bastante atenciosa aos detalhes 
            e extremamente educada, recomendo! <br /><br />
            <b>Serviço de Diarista:</b> Yuri Campos contratou um serviço de Santa Catarina, SC
          </p>
        </i>
      </div>
    </section>

    <section class="container-fluid card-container mt-5 mb-5">
      <div class="card m-auto text-center border rounded shadow" style="width: 18rem;">
        <img src="{% static 'base/img/card-img.png' %}" class="card-img-top" alt="..." />
        <div class="card-body">
          <i class="bi bi-tools"></i>
          <h5 class="card-title">Reforma e Reparos</h5>
          <p class="card-text">Serviços de Reformas e Reparos para a sua casa ou empresa. Os melhores profissionais.</p>
          <a href="#" class="btn btn-success">Ver Reforma e Reparos</a>
        </div>
      </div>
    </section>

    <section class="mt-5 mb-5">
      <div class="text-center">
        <h4>O que é a GYCIL?</h4>
        <p>GYCIL é uma plataforma de contratação de serviços de empresas do Brasil. Conectando diversas empresas com pessoas que necessitam de serviços e buscam facilidade e rapidez.</p>
      </div>

      <div class="container-sm mt-3 text-center">
        <span><i class="bi bi-credit-card"></i></span>
        <h5>Faça seu pedido</h5>
        <p>Fale o que você precisa. É rápido, é de graça!</p>
        <hr class="line" />

        <span><i class="bi bi-cash-coin"></i></span>
        <h5>Receba diversos orçamentos</h5>
        <p>Empresas avaliadas entram em contato com você em instantes!</p>
        <hr class="line" />

        <span><i class="bi bi-hand-thumbs-up"></i></span>
        <h5>Escolha o melhor</h5>
        <p>Negocie com as empresas, fácil como nunca visto antes!</p>
        <hr class="line" />
      </div>
    </section>
    {% if not user_type %}
      <section class="container-fluid mt-5 mb-3 rounded-2">
        <div class="card">
          <div class="card-body text-center rounded shadow">
            <div class="no-margin">
              <h4>Cadastre-se na GYCIL</h4>
            </div>
            <div>
              <div class="row space-between start-sm top-sm">
                <div class="col-sm-12 col-md-4">
                  <div class="col-sm-4 col-md-4 m-3">
                    <a href="{% url 'clients:create' %}" class="form-control submitBtn" type="submit" value="Cadastre-se">Cadastre-se como Cliente</a>
                  </div>
                  <div class="col-sm-4 col-md-4 m-3">
                    <a href="{% url 'companies:create' %}" class="form-control submitBtn" type="submit" value="Cadastre-se">Cadastre-se como Prestador de Serviço</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    {% endif %}

    {% comment %} <footer class="">
      <hr />
      <div class="text-center">
        <img class="img-fluid mb-5" width="80px" src="{% static 'base/img/logo_diamond_crop.png' %}" alt="" />
        <div class="text-center">
          <a href="">Ajuda</a>
        </div>
        <div class="text-center">
          <a href="">Termos de Uso</a>
        </div>
        <div class="text-center">
          <a href="">Política e Privacidade</a>
        </div>
      </div>
    </footer> {% endcomment %}
    {% include 'partials/_footer.html' %}
  </main>
{% endblock %}